repos:
- repo: local
  hooks:
    # Run the type checker (check for errors and warnings)
    - id: ty
      name: ty check
      entry: ty check
      language: system
      types: [python]
    # Run the linter (check for style issues)
    - id: ruff-check
      name: ruff check
      entry: ruff check
      language: system
      types: [python]
